#include <cpp11.hpp>
#include <cpp11/declarations.hpp>
#include <boost/math/distributions.hpp>
#include "boostmath/macros.hpp"

BINARY_DISTRIBUTION_BOOST(arcsine, double, double)
BINARY_DISTRIBUTION_BOOST(beta, double, double)
BINARY_DISTRIBUTION_BOOST(binomial, int, double)
BINARY_DISTRIBUTION_BOOST(cauchy, double, double)
UNARY_DISTRIBUTION_BOOST(chi_squared, double)
UNARY_DISTRIBUTION_BOOST(exponential, double)
BINARY_DISTRIBUTION_BOOST(extreme_value, double, double)
BINARY_DISTRIBUTION_BOOST(fisher_f, double, double)
BINARY_DISTRIBUTION_BOOST(gamma, double, double)
UNARY_DISTRIBUTION_BOOST(geometric, double)
BINARY_DISTRIBUTION_BOOST(holtsmark, double, double)
BINARY_DISTRIBUTION_BOOST(hyperexponential, std::vector<double>, std::vector<double>)
TERNARY_DISTRIBUTION_BOOST(hypergeometric, uint64_t, uint64_t, uint64_t)
BINARY_DISTRIBUTION_BOOST(inverse_chi_squared, double, double)
BINARY_DISTRIBUTION_BOOST(inverse_gamma, double, double)
BINARY_DISTRIBUTION_BOOST(inverse_gaussian, double, double)
UNARY_DISTRIBUTION_BOOST(kolmogorov_smirnov, int)
BINARY_DISTRIBUTION_BOOST(landau, double, double)
BINARY_DISTRIBUTION_BOOST(laplace, double, double)
BINARY_DISTRIBUTION_BOOST(logistic, double, double)
BINARY_DISTRIBUTION_BOOST(lognormal, double, double)
BINARY_DISTRIBUTION_BOOST(mapairy, double, double)
BINARY_DISTRIBUTION_BOOST(negative_binomial, double, double)
TERNARY_DISTRIBUTION_BOOST(non_central_beta, double, double, double)
BINARY_DISTRIBUTION_BOOST(non_central_chi_squared, double, double)
TERNARY_DISTRIBUTION_BOOST(non_central_f, double, double, double)
BINARY_DISTRIBUTION_BOOST(non_central_t, double, double)
BINARY_DISTRIBUTION_BOOST(normal, double, double)
BINARY_DISTRIBUTION_BOOST(pareto, double, double)
UNARY_DISTRIBUTION_BOOST(poisson, double)
UNARY_DISTRIBUTION_BOOST(rayleigh, double)
BINARY_DISTRIBUTION_BOOST(saspoint5, double, double)
TERNARY_DISTRIBUTION_BOOST(skew_normal, double, double, double)
UNARY_DISTRIBUTION_BOOST(students_t, double)
TERNARY_DISTRIBUTION_BOOST(triangular, double, double, double)
BINARY_DISTRIBUTION_BOOST(uniform, double, double)
BINARY_DISTRIBUTION_BOOST(weibull, double, double)
